app:
  image: ibmcom/swift-ubuntu:3.1.1
  volumes:
    - .:/CloudEnvironment
  command: bash -c "cd /CloudEnvironment && swift package --build-path .build-linux clean && swift build --build-path .build-linux && swift test --build-path .build-linux && swift package --build-path .build-linux clean"
